{% set name = "feature_engine" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 720dfd5679cdc8a3a9484c238fdcb3aab30d2cda44e7585ca5726db93fbe8d57

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.18.2
    - pandas >=1.0.3
    - scikit-learn >=0.22.2
    - scipy >=1.4.1
    - statsmodels >=0.11.1

test:
  imports:
    - feature_engine

about:
  home: https://github.com/feature-engine/feature_engine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Feature engineering and selection package with Scikit-learn's fit and transform functionality
  doc_url: https://feature-engine.trainindata.com

extra:
  recipe-maintainers:
    - solegalli
