{% set name = "feature_engine" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7f56abf92946f76c6855d026fb43c3efca5c1285084f7e87cb73adfdee0c189

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.18.2
    - pandas >=1.0.3
    - scikit-learn >=0.22.2
    - scipy >=1.4.1
    - statsmodels >=0.11.1

test:
  imports:
    - feature_engine

about:
  home: https://github.com/solegalli/feature_engine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Feature engineering package with Scikit-learn's fit transform functionality
  doc_url: http://feature-engine.readthedocs.io/

extra:
  recipe-maintainers:
    - solegalli
