{% set name = "feature_engine" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4a9a4bf51593df389972e4a7b8c40a971f1b87d28e1753fc0a58f3b74c993a4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.18.2
    - pandas >=1.0.3
    - scikit-learn >=0.22.2
    - scipy >=1.4.1
    - statsmodels >=0.11.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - feature_engine

about:
  home: https://github.com/feature-engine/feature_engine
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Feature engineering and selection package with Scikit-learn's fit and transform functionality
  doc_url: https://feature-engine.trainindata.com

extra:
  recipe-maintainers:
    - solegalli
